name: kyma-project.io/module/ai-sre
channel: fast
version: v1.0.0
manifest: template-operator.yaml
security: sec-scanners-config.yaml
defaultCR: ./config/samples/core_v1alpha1_k8sgpt.yaml
annotations:
  operator.kyma-project.io/doc-url: https://kyma-project.io