apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: ai-sre
spec:
  ai:
    enabled: true
    anonymized: false
    secret:
      name: openai-service
  version: v1.0.1